### ISSUE TITLE
Return from adding favorites in Product Listing doesn't work with Ultimate URLS

### ISSUE THREAD

**Issue by KilgoreLSU** [lat9/favorites_wishlist_support#4]
Adding works perfect on Product Page, but is not returning to Product Listing pages if using Ultimate URLS.

**Comment by lat9** [comment]
Yep, I 'broke' both the integration with "URL manglers" &mdash; e.g. USU and Ceon URI Mappings &mdash; as well as the return-to-where-you-came-from in v6.0.0.

**Comment by JeffMash** [comment]
I was just coming here to open this issue as well!

For me, the "fix" is to change the "**product_id=**" variable to "**pID=**" in admin/stats_favorites_wishlists.php on line 82.

Was:

`$favorites_info[$products_id]['product_link'] = zen_href_link($type_handler, "products_type=$products_type&cPath=$cPath&products_id=$products_id&action=new_product");`

To:

`$favorites_info[$products_id]['product_link'] = zen_href_link($type_handler, "products_type=$products_type&cPath=$cPath&pID=$products_id&action=new_product");`

**Comment by lat9** [comment]
Unfortunately, it's more complicated than that, since the listing add-to-favorites is _supposed to_ redirect either to the page on which the add-to-favorites was clicked or to the `shopping_cart` page, depending on the associated configuration setting.

That, plus the current issue is identifying mis-handling on the storefront, not the admin.

**Comment by lat9** [comment]
v6.0.1 just released; closing.
